spring:
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: salespage-schedule
debug: ${DEBUG:debug}

server:
  port: ${PORT:8080}


feign:
  domain: ${SERVER_DOMAIN:http:localhost:8080}
  client:
    config:
      gamiRequestFactory:
        connectTimeout: 5000
        readTimeout: 5000
      gameRequestFactory:
        connectTimeout: 5000
        readTimeout: 5000

